import streamlit as st

st.set_page_config(
    page_title="HSG Sim Datatool",
    page_icon="HSG",
    layout="centered"
)

hide_menu = """
<style>
#MainMenu {visibility:hidden;}
footer{visibility:hidden;}
</style>
"""
st.markdown(hide_menu, unsafe_allow_html=True)
st.markdown("""
<style>
.small-font-green {
    font-size:12px;
    color: green;
}
.small-font-red {
    font-size:12px;
    color: red;
}
.normal-font-red {
    font-size:16px;
    color: red;
}
.normal-font-green {
    font-size:16px;
    color: green;
}
</style>
""", unsafe_allow_html=True)

# Main area content
st.title("Terms and Conditions")
st.write(
    """
    Terms of Use for the HSGSim Data Tool
As of: June 17, 2025

§ 1 Scope and Provider

(1) These Terms of Use govern the use of the online tool (hereinafter "Service") provided free of charge on the website https://hsgdatatool.streamlit.app/.

(2) The provider of the Service is: University Group Simulation (hereinafter "Provider").

(3) By uploading data and using the Service, the user agrees to these Terms of Use. Deviating terms of the user will not be recognized unless the Provider expressly agrees to their validity in writing.

§ 2 Subject Matter of the Service

(1) The Provider provides the user with an online tool with which the user can upload anonymous measurement data (hereinafter "Data") and have it processed automatically. The type of processing and the possible results (e.g., analysis, visualization, conversion) are described in more detail on the website.

(2) The Service is provided exclusively free of charge. There is no entitlement to registration or use.

(3) The Provider is entitled to change, restrict, or completely discontinue the Service at any time and without giving reasons.

§ 3 Obligations and Responsibilities of the User

(1) The user is solely responsible for the data they upload.

(2) The user warrants that the data they upload does not contain any personal data within the meaning of the General Data Protection Regulation (GDPR) and does not allow any conclusions to be drawn about identifiable persons. The uploading of personal data is strictly prohibited.

(3) The user further warrants that the data they provide is free of third-party rights (in particular, copyrights and related rights) that would conflict with processing within the scope of this Service.

(4) The user is prohibited from misusing the Service. This includes, in particular, the uploading of data containing viruses, Trojans, or other malicious software, as well as attempts to disrupt or circumvent the functionality of the Service.

(5) The user is responsible for creating backup copies of the data they upload. The Provider assumes no responsibility for any data loss.

§ 4 Granting of Usage Rights

(1) By uploading the Data, the user grants the Provider a non-exclusive, worldwide, and royalty-free right to technically reproduce, edit, and process the uploaded anonymous data for the duration of use, insofar as this is necessary to provide the Service.

(2) The Provider is entitled to store the uploaded as well as the anonymous data generated by the Service in a completely anonymized form and to use it for its own purposes, such as improving the Service, for statistical analyses, or for scientific evaluations. It is not possible to trace this data back to the original user.

§ 5 Availability

The Provider strives to make the Service available with as few interruptions as possible. However, the user has no claim to constant and uninterrupted availability. The Provider gives no warranty for the accessibility of the Service and excludes all liability for downtime.

§ 6 Warranty and Liability

(1) The Service is provided "as is" and without any warranty. The Provider does not guarantee that the results generated by the Service are correct, complete, or suitable for the purpose intended by the user. The use of the results is at the user's own risk.

(2) As the Service is provided free of charge, the Provider's liability is severely limited. The Provider shall only be liable without limitation for intent and gross negligence.

(3) For simple negligence, the Provider shall only be liable in the event of a breach of a material contractual obligation (cardinal duty), the fulfillment of which is essential for the proper execution of the contract and on whose observance the user may regularly rely. In this case, liability is limited to the foreseeable damage typical for the contract.

(4) The foregoing limitations of liability do not apply in the case of injury to life, body, or health, for fraudulently concealed defects, or in the case of liability under the Product Liability Act.

(5) Insofar as the liability of the Provider is excluded or limited, this also applies to the personal liability of employees, representatives, and vicarious agents of the Provider.

§ 7 Final Provisions

(1) The law of the Federal Republic of Germany shall apply, to the exclusion of the UN Convention on Contracts for the International Sale of Goods (CISG).

(2) Should individual provisions of these Terms of Use be or become wholly or partially invalid, the validity of the remaining provisions shall not be affected thereby. The statutory provision shall take the place of the invalid provision.

(3) The Provider reserves the right to change these Terms of Use. Users will not be individually informed about changes. It is the user's responsibility to check the current version of the Terms of Use before each use. Continued use of the Service after a change is considered as consent to the new terms.
    
    """


)